### ISSUE TITLE
Pages with images takes long time to publish

### ISSUE THREAD

**Issue by ErikJJonsson** [7h3Rabbit/StaticWebEpiserverPlugin#76]
Pages with images takes long time to publish. The time increases for every image added.
Profiling shows that the method DownloadResource() is where the time is spent.
![trace_save](https://user-images.githubusercontent.com/48356833/164183349-98f7491d-2e52-4b09-bd1c-a8e0f9810322.png)

Would it be possible to make the resourse handling async?

**Comment by 7h3Rabbit** [comment]
Sounds weird that it would increase in time.
Can you supply example HTML of your page?
Making it async (and not waiting for result) would result in a page with broken images until they are downloaded, so probably not a good idea.
Have you session handling enabled on your EpiServer website? (asking because that could cause resource 3 to wait to resource 2 and 1 being downloaded first)

**Comment by ErikJJonsson** [comment]
We don't need this requested change anymore so I will close this issue.

**Comment by 7h3Rabbit** [comment]
@ErikJJonsson Can I ask why? *Curious* :)

**Comment by ErikJJonsson** [comment]
Changed requirements has made us changing the way we set up our environment.
Because of that we will not generate static pages which relies on resources fetched via API:s which was why publishing became slow.
